### ISSUE TITLE
admin modu

### ISSUE THREAD

**Issue by turret001** [umithyo/mta-tr#2]
adminlere ateş edilince canları gidiyor bence buna bir çözüm bulunmalı

**Comment by umithyo** [comment]
repoyu public yapmak icin eski commitleri sifirladim ondan dolayi bir sikinti yasanmis olabilir tekrar deneyelim @turret001

**Comment by turret001** [comment]
kusura bakmayın bende tekrar deneyecek enerji kalmadı, hakkınızı helal edin.
